site_name: CSVW Safe
site_description: CSVW Safe vocabulary and library
site_url: https://dscc-admin-ch.github.io/csvw-safe-docs/

theme:
  name: material

nav:
  - Home: index.md
  - Vocabulary: vocabulary.md
  - Library: library.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code

docs_dir: docs
site_dir: site