nav:
  - Home: index.md

  - Vocabulary:
      - Overview: vocabulary.md

  - Library:
      - Overview: library.md

  - Tutorials:
      - Basic Workflow: tutorials/basic_workflow.md
      - DP Contribution Levels: tutorials/dp_contributions.md
      - Synthetic Generation: tutorials/synthetic_generation.md

  - API Reference:
      - Overview: api/index.md
      - Metadata Generation: api/metadata_generation.md
      - Dummy Generation: api/dummy_generation.md
      - Validation: api/validation.md
      - OpenDP: api/opendp.md
      - SmartNoise SQL: api/smartnoise.md
      - Metadata Models: api/models.md
      - Utilities: api/utilities.md