name: Build and publish docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material

      - name: Prepare documentation
        run: |
          chmod +x scripts/prepare-docs.sh
          ./scripts/prepare-docs.sh

      - name: Build site
        run: |
          mkdocs build

      - name: Push to docs repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_DOCS }}
        with:
          source-directory: site/
          destination-github-username: dscc-admin-ch
          destination-repository-name: csvw-safe-docs
          target-branch: main