name: Run Tests

on:
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd csvw-safe-library
          pip install -e .[dev]

      - name: Run tests with coverage
        run: |
          cd csvw-safe-library
          coverage run -m pytest . -vv
          coverage xml

      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERAGE_PATH: csvw-safe-library/
          MINIMUM_GREEN: 90
          MINIMUM_ORANGE: 80